### ISSUE TITLE
Will not write a save.

### ISSUE THREAD

**Issue by GinBunBun** [mlarouche/ChronoTrigger-MSU1#1]
When using this on the SD2SNES flash cart. When ever you save your game it appears fine but when you shut it off or reset the save is gone. I don't think it actually writes the save at all. The same problem happens with the Legend Of Zelda A Link To The Past MSU1 hack if you don't expand the rom. I tried doing that with chrono trigger and it didn't fix it either.

**Comment by DoctorDan1986** [comment]
One of the known limitations of the MSU-1 enhancement is that you need to
use the old reset method, ie, either holding the reset button in, or using
the SD2SNES built-in reset method after saving your game the normal way.
This is not a problem with the patch.

**Comment by mlarouche** [comment]
Like DoctorDan said, it's an known issue with the SD2SNES
