### ISSUE TITLE
Audio needs editing. Maybe use Sox?

### ISSUE THREAD

**Issue by Dizzy611** [mlarouche/ChronoTrigger-MSU1#4]
There's some fairly obvious parts where the audio needs to be edited, mostly trimmed.

For an example, the premonition comes in so gradually that it's nowhere near done by the time the emulator is done playing it, leaving most of that sequence silent.

Also, you haven't defined any loop points in your PCMs.

As far as trimming samples, this can be done in a batch file with sox (http://sox.sourceforge.net/), and then, having trimmed the samples to fit, loop points can be set with wav2msu itself.

**Comment by mlarouche** [comment]
Hey that's a good idea ! I thought about patching the WAV files with byuu patch format but this is better :) I could also force a volume boost at the same time.

**Comment by mlarouche** [comment]
This is now done since 28c9cbbdb26f7724a938ccf8ed64b6cce21994c3 :)
