### ISSUE TITLE
bml file missing

### ISSUE THREAD

**Issue by gillotte** [mlarouche/ChronoTrigger-MSU1#5]
a bml file isn't provided for higan

**Comment by baconnc** [comment]
It also seems like. The file chrono_msu1.msu is missing.  Unless I am supposed to get that elsewhere?

**Comment by gillotte** [comment]
Most of the ones I've seen have had 0 byte msu files as simply placeholders.

I've been trying to construct a working bml and I havent had any luck yet.
though I've been able to get the patch working in bsnes 075 just fine. I
wonder why newer versions of the emulator added so much complexity.

-john

**Comment by mlarouche** [comment]
I added it with 22c014cd62dc96ace586b13939616a1f6ff35976

**Comment by gillotte** [comment]
thanks for fixing!
