### ISSUE TITLE
wav2msu binary?

### ISSUE THREAD

**Issue by polyh3dron** [mlarouche/ChronoTrigger-MSU1#7]
The readme links to a GitHub repo for wav2msu but it has no binary in it. I googled wav2msu and found one, but its command line syntax is different and therefore the batch files for this hack don't work with it.

**Comment by ratix00** [comment]
[wav2msu.zip](https://github.com/mlarouche/ChronoTrigger-MSU1/files/190628/wav2msu.zip)
github seems to have deleted .exe file types.
This file is the same file i've used to convert several times with the game it should work.

**Comment by mlarouche** [comment]
I bundle my wav2msu with the official Chrono Trigger hack release, see here:

http://www.romhacking.net/hacks/2546/
